/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Kiểm tra API còn chạy */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Người đang đăng nhập, lấy từ token
     * @description Không đọc dữ liệu: mọi thông tin lấy từ token Cognito mà JWT authorizer của HTTP API đã kiểm. `email` chỉ có khi gửi ID token; access token của Cognito không chứa email.
     */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Danh sách sản phẩm (có lọc, tìm theo tên và phân trang)
     * @description Chỉ trả sản phẩm ACTIVE. Dùng được cùng lúc `category` và `q`.
     *     Tìm theo tên không phân biệt chữ hoa, chữ thường và dấu tiếng Việt,
     *     khớp ở bất kỳ vị trí nào trong tên (catalog.md BR-03).
     */
    get: operations['listProducts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/{productId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chi tiết sản phẩm */
    get: operations['getProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Xem giỏ hàng của người đang đăng nhập */
    get: operations['getCart'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Thêm sản phẩm vào giỏ (cộng dồn nếu đã có)
     * @description Số lượng sau khi cộng dồn không vượt quá min(99, tồn kho) (cart.md BR-03, BR-04).
     *     Giỏ tối đa 50 dòng (BR-02).
     */
    post: operations['addCartItem'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/merge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Gộp giỏ khách vãng lai vào giỏ tài khoản sau khi đăng nhập
     * @description Gọi một lần ngay sau khi đăng nhập hoặc tạo tài khoản, gửi toàn bộ giỏ khách đang lưu
     *     trên trình duyệt (cart.md BR-01, BR-10). Món đã có thì cộng dồn nhưng không vượt
     *     min(99, tồn kho); món mới thêm nếu giỏ còn dưới 50 dòng; món ngừng bán, hết hàng hoặc
     *     không tồn tại thì bỏ qua. Không trả 409 cho từng món: mọi điều chỉnh nằm trong `adjustments`.
     *     Bắt buộc header Idempotency-Key (UUID v4): gọi lại cùng khoá trả cùng kết quả,
     *     không cộng dồn lần hai.
     */
    post: operations['mergeCart'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/items/{productId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Cập nhật số lượng sản phẩm trong giỏ */
    put: operations['updateCartItem'];
    post?: never;
    /** Xoá sản phẩm khỏi giỏ */
    delete: operations['removeCartItem'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lịch sử đơn hàng của người đang đăng nhập */
    get: operations['listOrders'];
    put?: never;
    /**
     * Tạo đơn hàng từ các sản phẩm đã chọn trong giỏ
     * @description Client gửi danh sách sản phẩm muốn đặt (chỉ những món đã tick chọn trong giỏ)
     *     kèm giá đang hiển thị (`expectedPrice`). Trong một giao dịch, server kiểm tồn kho
     *     và giá, trừ kho, tạo đơn và xoá các món đã đặt khỏi giỏ (ordering.md BR-03, BR-07, BR-08).
     *     Miễn phí vận chuyển. Bắt buộc header Idempotency-Key (UUID v4).
     */
    post: operations['createOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{orderId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chi tiết một đơn hàng */
    get: operations['getOrder'];
    put?: never;
    post?: never;
    /**
     * Huỷ đơn hàng của mình (khi status là PENDING hoặc CONFIRMED)
     * @description Huỷ thành công thì hoàn lại tồn kho và gửi email báo khách (ordering.md BR-10, BR-12, BR-13).
     */
    delete: operations['cancelOrder'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    ProductCategory:
      | 'laptop'
      | 'cpu'
      | 'gpu'
      | 'ram'
      | 'storage'
      | 'mainboard'
      | 'psu'
      | 'cooling'
      | 'keyboard'
      | 'mouse'
      | 'monitor'
      | 'headset'
      | 'accessory';
    /** @enum {string} */
    ProductStatus: 'ACTIVE' | 'INACTIVE';
    /**
     * @description Thông tin rút gọn cho danh sách sản phẩm
     * @example {
     *       "productId": "01J9XKPQ0000000000000001",
     *       "name": "ASUS TUF Gaming GeForce RTX 4070",
     *       "category": "gpu",
     *       "brand": "ASUS",
     *       "price": 15900000,
     *       "stock": 12,
     *       "status": "ACTIVE",
     *       "imageUrl": "https://placehold.co/400x300?text=RTX+4070"
     *     }
     */
    ProductSummary: {
      /**
       * @description ULID
       * @example 01J9XKPQ0000000000000001
       */
      productId: string;
      /** @example ASUS TUF Gaming GeForce RTX 4070 */
      name: string;
      category: components['schemas']['ProductCategory'];
      /** @example ASUS */
      brand: string;
      /**
       * @description Giá niêm yết (VND, số nguyên)
       * @example 15900000
       */
      price: number;
      /** @example 12 */
      stock: number;
      status: components['schemas']['ProductStatus'];
      /**
       * Format: uri
       * @example https://placehold.co/400x300?text=RTX+4070
       */
      imageUrl?: string;
    };
    Product: components['schemas']['ProductSummary'] & {
      /** @example Card đồ hoạ ASUS TUF Gaming RTX 4070 12GB GDDR6X, phù hợp gaming 1440p và dựng hình. */
      description: string;
      /**
       * @description Thông số kỹ thuật tuỳ theo category
       * @example {
       *       "vram": "12GB GDDR6X",
       *       "tdp": "200W",
       *       "connector": "PCIe 4.0 x16"
       *     }
       */
      specs?: {
        [key: string]: unknown;
      };
      /**
       * Format: date-time
       * @example 2026-10-01T07:00:00Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-10-01T07:00:00Z
       */
      updatedAt: string;
    };
    /**
     * @example {
     *       "productId": "01J9XKPQ0000000000000001",
     *       "name": "ASUS TUF Gaming GeForce RTX 4070",
     *       "imageUrl": "https://placehold.co/400x300?text=RTX+4070",
     *       "price": 15900000,
     *       "quantity": 1,
     *       "stock": 12,
     *       "status": "ACTIVE",
     *       "priceChanged": false
     *     }
     */
    CartItem: {
      /** @example 01J9XKPQ0000000000000001 */
      productId: string;
      /** @example ASUS TUF Gaming GeForce RTX 4070 */
      name: string;
      /**
       * Format: uri
       * @example https://placehold.co/400x300?text=RTX+4070
       */
      imageUrl?: string;
      /**
       * @description Giá hiện tại lấy từ bảng products (VND)
       * @example 15900000
       */
      price: number;
      /** @example 1 */
      quantity: number;
      /**
       * @description Tồn kho hiện tại; nhỏ hơn quantity thì món này chưa đặt được (cart.md BR-07)
       * @example 12
       */
      stock: number;
      status: components['schemas']['ProductStatus'];
      /**
       * @description true nếu giá thay đổi kể từ lần thêm vào giỏ
       * @example false
       */
      priceChanged?: boolean;
    };
    /**
     * @example {
     *       "totalAmount": 16550000,
     *       "items": [
     *         {
     *           "productId": "01J9XKPQ0000000000000001",
     *           "name": "ASUS TUF Gaming GeForce RTX 4070",
     *           "imageUrl": "https://placehold.co/400x300?text=RTX+4070",
     *           "price": 15900000,
     *           "quantity": 1,
     *           "stock": 12,
     *           "status": "ACTIVE",
     *           "priceChanged": false
     *         },
     *         {
     *           "productId": "01J9XKPQ0000000000000002",
     *           "name": "Chuột Logitech G502 X Plus",
     *           "imageUrl": "https://placehold.co/400x300?text=G502+X",
     *           "price": 650000,
     *           "quantity": 1,
     *           "stock": 5,
     *           "status": "ACTIVE",
     *           "priceChanged": false
     *         }
     *       ]
     *     }
     */
    Cart: {
      items: components['schemas']['CartItem'][];
      /**
       * @description Tổng tiền (VND) — chỉ tính món ACTIVE có stock >= quantity
       * @example 16550000
       */
      totalAmount: number;
    };
    /**
     * @example {
     *       "items": [
     *         {
     *           "productId": "01J9XKPQ0000000000000001",
     *           "quantity": 1
     *         },
     *         {
     *           "productId": "01J9XKPQ0000000000000002",
     *           "quantity": 2
     *         }
     *       ]
     *     }
     */
    MergeCartRequest: {
      /** @description Toàn bộ giỏ khách; mỗi productId xuất hiện một lần */
      items: {
        productId: string;
        quantity: number;
      }[];
    };
    /** @description Một món trong giỏ khách không được gộp đúng như yêu cầu */
    MergeAdjustment: {
      productId: string;
      /**
       * @description `QUANTITY_LIMITED` cộng dồn vượt min(99, tồn kho), đã chặn ·
       *     `PRODUCT_UNAVAILABLE` ngừng bán · `OUT_OF_STOCK` hết hàng ·
       *     `NOT_FOUND` không còn trong catalog · `CART_FULL` giỏ đã đủ 50 dòng
       * @enum {string}
       */
      reason:
        'QUANTITY_LIMITED' | 'PRODUCT_UNAVAILABLE' | 'OUT_OF_STOCK' | 'NOT_FOUND' | 'CART_FULL';
      /** @description Số lượng trong giỏ khách */
      requested: number;
      /** @description Số lượng thực sự cộng thêm vào giỏ tài khoản (0 nếu bỏ qua) */
      merged: number;
    };
    /**
     * @example {
     *       "cart": {
     *         "totalAmount": 16550000,
     *         "items": [
     *           {
     *             "productId": "01J9XKPQ0000000000000001",
     *             "name": "ASUS TUF Gaming GeForce RTX 4070",
     *             "imageUrl": "https://placehold.co/400x300?text=RTX+4070",
     *             "price": 15900000,
     *             "quantity": 1,
     *             "stock": 12,
     *             "status": "ACTIVE",
     *             "priceChanged": false
     *           },
     *           {
     *             "productId": "01J9XKPQ0000000000000002",
     *             "name": "Chuột Logitech G502 X Plus",
     *             "imageUrl": "https://placehold.co/400x300?text=G502+X",
     *             "price": 650000,
     *             "quantity": 2,
     *             "stock": 5,
     *             "status": "ACTIVE",
     *             "priceChanged": false
     *           }
     *         ]
     *       },
     *       "mergedExisting": [],
     *       "adjustments": []
     *     }
     */
    MergeCartResult: {
      cart: components['schemas']['Cart'];
      /** @description productId của các món đã có sẵn trong giỏ tài khoản nên được cộng dồn */
      mergedExisting?: string[];
      adjustments: components['schemas']['MergeAdjustment'][];
    };
    Me: {
      /**
       * @description sub của Cognito, cố định suốt đời tài khoản
       * @example f1b2c3d4-0000-4000-8000-000000000001
       */
      userId: string;
      /** Format: email */
      email?: string;
      /**
       * @example [
       *       "admin"
       *     ]
       */
      groups: string[];
    };
    /** @description Lỗi theo RFC 9457 */
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** @description Mã lỗi nghiệp vụ để frontend xử lý, ví dụ OUT_OF_STOCK, PRICE_CHANGED */
      code?: string;
      traceId?: string;
      /** @description Chi tiết lỗi theo từng trường khi input sai */
      errors?: {
        field: string;
        message: string;
      }[];
    };
    CartProblem: components['schemas']['Problem'] & {
      /** @enum {string} */
      code?: 'QUANTITY_LIMIT' | 'PRODUCT_UNAVAILABLE' | 'CART_FULL';
      /** @description Số lượng còn thêm được vào giỏ (khi QUANTITY_LIMIT) */
      maxAddable?: number;
    };
    OrderProblem: components['schemas']['Problem'] & {
      /** @enum {string} */
      code?: 'OUT_OF_STOCK' | 'PRICE_CHANGED' | 'ORDER_IN_PROGRESS';
      /** @description Món hết hàng, không đủ số lượng hoặc ngừng bán (khi OUT_OF_STOCK) */
      invalidItems?: {
        productId: string;
        /** @description Số còn đặt được; 0 nếu hết hàng hoặc ngừng bán */
        available: number;
      }[];
      /** @description Món đã đổi giá (khi PRICE_CHANGED) */
      changedItems?: {
        productId: string;
        expectedPrice: number;
        currentPrice: number;
      }[];
    };
    ShippingAddress: {
      /**
       * @description Họ và tên người nhận
       * @example Nguyễn Văn A
       */
      fullName: string;
      /**
       * @description Số điện thoại Việt Nam, đã bỏ khoảng trắng (0xxxxxxxxx hoặc +84xxxxxxxxx)
       * @example 0912345678
       */
      phone: string;
      /**
       * @description Số nhà, tên đường, phường/xã
       * @example 12 Nguyễn Huệ, phường Bến Nghé
       */
      address: string;
      /**
       * @description Tỉnh / thành phố
       * @example TP. Hồ Chí Minh
       */
      province: string;
    };
    /** @enum {string} */
    OrderStatus: 'PENDING' | 'CONFIRMED' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED';
    /** @description Snapshot sản phẩm tại thời điểm đặt hàng */
    OrderItem: {
      productId: string;
      name: string;
      /** @description Giá tại thời điểm đặt (VND) */
      price: number;
      quantity: number;
    };
    /** @description Thông tin rút gọn cho danh sách đơn hàng */
    OrderSummary: {
      /** @description ULID */
      orderId: string;
      status: components['schemas']['OrderStatus'];
      /** @description Tổng tiền (VND) */
      totalAmount: number;
      /** @description Số loại sản phẩm trong đơn */
      itemCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    Order: {
      /** @description ULID */
      orderId: string;
      userId: string;
      status: components['schemas']['OrderStatus'];
      items: components['schemas']['OrderItem'][];
      /** @description Tổng tiền (VND), server tự tính; khách trả đúng số này khi nhận hàng */
      totalAmount: number;
      /**
       * @description Phí vận chuyển (VND); luôn 0 trong MVP (ordering.md BR-06)
       * @enum {integer}
       */
      shippingFee: 0;
      shippingAddress: components['schemas']['ShippingAddress'];
      /** @enum {string} */
      paymentMethod: 'COD';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: {
    /**
     * @description Thiếu token, token sai hoặc hết hạn. JWT authorizer của HTTP API chặn trước khi tới Lambda
     *     (ADR-0007) và trả body cố định, **không** theo RFC 9457: HTTP API không có Gateway Responses,
     *     CloudFront cũng không cho đổi body lỗi 401. Client chỉ dựa vào mã 401.
     */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @example Unauthorized */
          message: string;
        };
      };
    };
    /** @description Lỗi */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API đang chạy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok';
          };
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Thông tin người đang đăng nhập */
      200: {
        headers: {
          'Cache-Control'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
      401: components['responses']['Unauthorized'];
      default: components['responses']['Problem'];
    };
  };
  listProducts: {
    parameters: {
      query?: {
        /**
         * @description Từ khoá tìm trong tên sản phẩm, ví dụ `rtx` hoặc `chuot`
         * @example rtx
         */
        q?: string;
        /** @description Lọc theo loại sản phẩm */
        category?: components['schemas']['ProductCategory'];
        /**
         * @description Cách sắp xếp (catalog.md BR-08). Với mọi cách, sản phẩm hết hàng luôn nằm cuối.
         *     `newest` mới nhất trước · `price_asc` giá tăng dần · `price_desc` giá giảm dần
         */
        sort?: 'newest' | 'price_asc' | 'price_desc';
        /** @description Số sản phẩm mỗi trang (mặc định 20, tối đa 50) */
        limit?: number;
        /** @description Con trỏ phân trang từ response trước */
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Danh sách sản phẩm */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "items": [
           *         {
           *           "productId": "01J9XKPQ0000000000000001",
           *           "name": "ASUS TUF Gaming GeForce RTX 4070",
           *           "category": "gpu",
           *           "brand": "ASUS",
           *           "price": 15900000,
           *           "stock": 12,
           *           "status": "ACTIVE",
           *           "imageUrl": "https://placehold.co/300x200?text=RTX+4070"
           *         },
           *         {
           *           "productId": "01J9XKPQ0000000000000002",
           *           "name": "Chuột Logitech G502 X Plus Wireless",
           *           "category": "mouse",
           *           "brand": "Logitech",
           *           "price": 1890000,
           *           "stock": 25,
           *           "status": "ACTIVE",
           *           "imageUrl": "https://placehold.co/300x200?text=G502+X"
           *         },
           *         {
           *           "productId": "01J9XKPQ0000000000000003",
           *           "name": "SSD Samsung 990 Pro 1TB NVMe M.2",
           *           "category": "storage",
           *           "brand": "Samsung",
           *           "price": 2450000,
           *           "stock": 8,
           *           "status": "ACTIVE",
           *           "imageUrl": "https://placehold.co/300x200?text=990+Pro"
           *         },
           *         {
           *           "productId": "01J9XKPQ0000000000000004",
           *           "name": "RAM Corsair Vengeance DDR5 32GB 5600MHz",
           *           "category": "ram",
           *           "brand": "Corsair",
           *           "price": 3200000,
           *           "stock": 0,
           *           "status": "ACTIVE",
           *           "imageUrl": "https://placehold.co/300x200?text=DDR5+32GB"
           *         }
           *       ]
           *     }
           */
          'application/json': {
            items: components['schemas']['ProductSummary'][];
            /** @description Có giá trị nếu còn trang tiếp theo */
            nextCursor?: string;
          };
        };
      };
      400: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        productId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chi tiết sản phẩm */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Product'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Giỏ hàng hiện tại */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      401: components['responses']['Unauthorized'];
      default: components['responses']['Problem'];
    };
  };
  addCartItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          productId: string;
          quantity: number;
        };
      };
    };
    responses: {
      /** @description Giỏ hàng sau khi cập nhật */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['Problem'];
      /**
       * @description `QUANTITY_LIMIT` vượt min(99, tồn kho), kèm `maxAddable` ·
       *     `PRODUCT_UNAVAILABLE` sản phẩm đã ngừng bán · `CART_FULL` giỏ đã đủ 50 dòng
       */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['CartProblem'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  mergeCart: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID v4 do client sinh cho mỗi lần gộp */
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MergeCartRequest'];
      };
    };
    responses: {
      /** @description Giỏ tài khoản sau khi gộp, kèm các món bị điều chỉnh */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MergeCartResult'];
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Unauthorized'];
      /**
       * @description `MERGE_IN_PROGRESS` lần gộp trước với cùng Idempotency-Key chưa xong; giữ nguyên khoá
       *     và thử lại sau (web giữ giỏ khách, khách bấm "Gộp vào giỏ")
       */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `IDEMPOTENCY_KEY_REUSED` cùng khoá nhưng nội dung khác */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  updateCartItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        productId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          quantity: number;
        };
      };
    };
    responses: {
      /** @description Giỏ hàng sau khi cập nhật */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['Problem'];
      /** @description `QUANTITY_LIMIT` số lượng mới vượt min(99, tồn kho), kèm `maxAddable` */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['CartProblem'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  removeCartItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        productId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Giỏ hàng sau khi xoá */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listOrders: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Danh sách đơn hàng */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['OrderSummary'][];
            nextCursor?: string;
          };
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Unauthorized'];
      default: components['responses']['Problem'];
    };
  };
  createOrder: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID v4 do client sinh, dùng để chống tạo đơn trùng khi retry */
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Danh sách sản phẩm đã chọn (chỉ những món tick ☑ trong giỏ) */
          items: {
            productId: string;
            quantity: number;
            /** @description Đơn giá (VND) khách đang thấy; khác giá hiện tại thì trả 409 PRICE_CHANGED */
            expectedPrice: number;
          }[];
          shippingAddress: components['schemas']['ShippingAddress'];
        };
      };
    };
    responses: {
      /** @description Đơn hàng cũ (trùng Idempotency-Key — đã xử lý rồi) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Order'];
        };
      };
      /** @description Đơn hàng mới được tạo */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Order'];
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Unauthorized'];
      /**
       * @description `OUT_OF_STOCK` có món hết hàng, không đủ số lượng hoặc ngừng bán, kèm `invalidItems` ·
       *     `PRICE_CHANGED` giá đã đổi, kèm `changedItems` · `ORDER_IN_PROGRESS` lần gửi trước
       *     với cùng Idempotency-Key chưa xong, giữ nguyên khoá và thử lại sau
       */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['OrderProblem'];
        };
      };
      /** @description `IDEMPOTENCY_KEY_REUSED` cùng Idempotency-Key nhưng nội dung đơn khác */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chi tiết đơn hàng */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Order'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  cancelOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Đơn đã bị huỷ */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Order'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['Problem'];
      /** @description `CANNOT_CANCEL` đơn đã SHIPPED, DELIVERED hoặc đã CANCELLED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
}
